import Head from "next/head";
import { Box, Button } from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box>
          <Button variant="contained" color="primary">
            hoge
          </Button>
        </Box>
      </main>
    </>
  );
}
